name: macos-matrix

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "ma*" ]

env:
  CARGO_TERM_COLOR: always
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-15-intel, macos-latest]
        feature: ["default", "model-xs", "model-s", "model-ds", "model-m", "model-deep", "model-xl", "model-l"]

    steps:
    - uses: actions/checkout@v4
    - name: Build ${{ matrix.feature }}
      run: cargo build --verbose
    - name: Test ${{ matrix.feature }}
      run: |
        if [[ "${{ matrix.feature }}" == "default" ]]; then
          cargo test --verbose
        else
          cargo test --verbose -- --${{ matrix.feature }}
        fi
      #continue-on-error: true
