name: Rust

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-15-intel, macos-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Build/Test
      run: cargo build --verbose && cargo test
      continue-on-error: true
    - name: Build/Test (model-xs feature)
      run: cargo build --features model-xs --verbose && cargo test --features model-xs
      continue-on-error: true
    - name: Build/Test (model-s feature)
      run: cargo build --features model-s --verbose && cargo test --features model-s
      continue-on-error: true
